### ISSUE TITLE
Can this fix the problem with file upload in webview?

### ISSUE THREAD

**Issue by osiris22** [delight-im/Android-AdvancedWebView#10]
Hi, I was trying to use your script to fix the problem with filechooser for example:
 if I open this page in the browser http://www.francesco.iovine.name/w3c/mediacapture/ and try to upload something it's works the way it should.

But in your script it takes me to the choose a recent document instead of choose an application to complete the action. Like Camera or Audio Recorder.

I feel like I'm doing something wrong, but want to make sure, I spend so much time on this problem, all I'm trying to do is to load one page inside the app and make input field work the way it should.

I would appreciate for any help. Thank you

**Comment by mwaclawek** [comment]
Thanks for this feature request!

You're right, this would definitely be nice to have. Unfortunately, it may not be that easy to implement.

 * Detecting if content is to be captured from camera/camcorder/microphone
   * On Android 5.0 and above, detecting the capture request is easy: In the `onShowFileChooser()` method that this library implements, we can just check whether `fileChooserParams.isCaptureEnabled()` is set to `true`. In addition, one can use `fileChooserParams.getAcceptTypes()` to check whether an image, a video or audio should be captured.
   * On Android 4.3 and before, detecting the capture request is not that simple: If you're lucky, Android calls the `openFileChooser()` version that has three parameters, which this library implements as well. The second parameter, `acceptType`, again lets us detect whether image, video or audio is requested. The third parameter, `capture`, seems to be set to `filesystem` by default. It just takes what was set in the `capture=""` attribute in HTML. The problem is that you cannot distinguish an *empty* `capture` attribute from a *missing* `capture` attribute: In both cases, the parameter in Android will be set to `filesystem`.
   * So in general, if we want to add the capture feature, we should *always* offer the feature *in addition to* the normal file picker on Android 2.2 to Android 4.3. This is what Firefox for Android [is doing as well](https://developer.mozilla.org/de/docs/Web/HTML/Element/Input#Gecko_notes). On Android 5.0+, we may use the value of `fileChooserParams.isCaptureEnabled()` which is reliable.
 * Capturing content from camera/camcorder/microphone
   * Capturing a photo seems to be [a little bit complex](http://developer.android.com/training/camera/photobasics.html) as you must have the permission `android.permission.WRITE_EXTERNAL_STORAGE`, create the file in advance and then pass this file to the component taking the photo so that it can save the captured image there.
   * Capturing a video seems to be [very simple](http://developer.android.com/training/camera/videobasics.html).
   * Capturing audio seems to be [the most complex](http://developer.android.com/guide/topics/media/audio-capture.html) but it's also the least frequently used, fortunately.

All in all, you see that this is not that easy. For the normal file picker, we can provide this out of the box and it doesn't require any permissions or adjustments. But for these content capture methods, things look different.

**Comment by osiris22** [comment]
Awesome thank you for great reply can't wait to try this out. For my project I need to upload audio recorded from voice recorder which one built-in in android. But so far no luck even on lollipop but I feel like I was doing something wrong. Thank you again

**Comment by augustusbuckman** [comment]
hello there am using the advanced WebView but it doesnt allow me to upload a file or image.wen i click on upload,nothing shows up.the page is just still... please help me fix issue

**Comment by mwaclawek** [comment]
Thanks for your feedback, @augustusbuckman! Maybe you should create a separate issue for this. We can discuss your specific problem there after you have created the new issue :) Please include information about the Android version that you're testing this on. Thank you!
