### ISSUE TITLE
How to hide the title bar with blue background

### ISSUE THREAD

**Issue by shiniandaohai** [delight-im/Android-AdvancedWebView#106]
As the title,I don't need the title bar. How to hide it?
thank you.

**Comment by ocram** [comment]
Which title bar? Can you post a screenshot or describe it more precisely? Thank you!

**Comment by shiniandaohai** [comment]
<img width="369" alt="071958b9-83d6-4710-a69d-4819eb7993e4" src="https://cloud.githubusercontent.com/assets/25241607/22179566/9daa1c72-e092-11e6-8dbe-6f8e27683913.png">
@ocram the blue bar of this screenshot,thank you.

**Comment by ocram** [comment]
Thanks!

That bar is not from this library itself, for sure. The sample included in this repository does not include such a bar, either.

So that bar must be some Android `View` above the `WebView` instance *or* it must actually be *part* of the web content displayed inside the `WebView`. From the look of that bar, I'd say the latter option is the most likely. So it's probably part of the web page that you display.

Anyway, it's not something we have caused here or that we can change here.

Hope that helps!
