### ISSUE TITLE
How to disable remote debugging of AdvancedWebView (chrome dev tools)

### ISSUE THREAD

**Issue by sudheeshde** [delight-im/Android-AdvancedWebView#107]
HI, is there a way to disable remote debugging of webview using dev tools in chrome ?
My app shows debugging in chrome dev tools even after I'm writing the below code 

`AdvancedWebView.setWebContentsDebuggingEnabled(false);`

please reply asap.
Thanks in advance

chrome remote debugging android webview
[https://developers.google.com/web/tools/chrome-devtools/remote-debugging/](url)

**Comment by ocram** [comment]
We didn't make any changes to Android's built-in `WebView` in that regard.

But, as far as I know, if you're running a *debug build* of your app, remote debugging will always be available. In order to turn it off, you thus have to call the method that you called *and* export a *release build*.

Hope that helps!
