### ISSUE TITLE
FileUpload on Android 4.4.2 does not work

### ISSUE THREAD

**Issue by ddinger** [delight-im/Android-AdvancedWebView#11]
Just tried your code on my LG G2 running Android 4.4.2 with an html containing input type=fileupload.
Unfortunately nothing happend, when I clicked on the "Upload" Button.

Kind regards,
Dirk

**Comment by Soukiy** [comment]
any solution for this ?
im have same issues, i need a solution for FileUpload on 4.4.2. other version work fine.... but my client is calling and i can't figure out with a solution.

**Comment by mwaclawek** [comment]
This is a real shame, but unfortunately, there is *no* possibility to make file upload works on Android 4.4.x.

This is because the APIs that worked from Android 2.2 to Android 4.3 have been removed in Android 4.4 and a new API for file uploads has only been introduced in Android 5.0.

With this library, you get working file uploads for all these versions out of the box, just except for Android 4.4.x.

See this issue as well: https://github.com/delight-im/Android-AdvancedWebView/issues/4
