### ISSUE TITLE
Missing content_type in file upload with Android 4.4.4

### ISSUE THREAD

**Issue by neonmate** [delight-im/Android-AdvancedWebView#14]
Hello,

I am trying to upload images via a WebView in Android. Both your implementation as http://stackoverflow.com/questions/5907369/file-upload-in-webview are not properly working for me with Android 4.4.4. Here is an extract from the received data:

**Android 4.4.4**

    Parameters: {"utf8"=>"✓", "authenticity_token"=>"Vximz1fjqQcRpeYvek3G3tfK2L9wiQQSm837Zj5+aBI=", "item"=>{"image"=>#<ActionDispatch::Http::UploadedFile:0x007f2e49ab35f0 @tempfile=#<Tempfile:/tmp/RackMultipart20150228-10308-h8g0yc>, @original_filename="image:1641", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"item[image]\"; filename=\"image%3A1641\"\r\nContent-Type: application/octet-stream\r\n">, "description"=>"", "for_friends"=>"0", "for_family"=>"0", "for_acquaintances"=>"0"}, "commit"=>"Speichern", "user_id"=>"1"}

**Android 5.0**

    Parameters: {"utf8"=>"✓", "authenticity_token"=>"f/5PkwJ+g/30G7oWrsUizn0Lh7jzMsGMxnz264NorzQ=", "item"=>{"image"=>#<ActionDispatch::Http::UploadedFile:0x007f2e4a771710 @tempfile=#<Tempfile:/tmp/RackMultipart20150228-10308-1uacuce>, @original_filename="IMG_20150228_161113.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"item[image]\"; filename=\"IMG_20150228_161113.jpg\"\r\nContent-Type: image/jpeg\r\n">, "description"=>"", "for_friends"=>"0", "for_family"=>"0", "for_acquaintances"=>"0"}, "commit"=>"Speichern", "user_id"=>"1"}

The problem is the missing content type. Not even the filename has a content type extension. I tried things like setting the content type in the WebView manually with

    setType("image/jpeg");

But that approach doesn't work. Perhaps you know a solution for this issue. Thanks!

**Comment by mwaclawek** [comment]
Thanks for the feedback!

Unfortunately, you already have it working as well as it's possible. With the native `WebView` component in Android, you will never achieve better results on Android 4.4.4. It's just like that, there's a bug.

As you know, file uploads have been working from Android 2.2 to 4.3 but stopped working in 4.4. However, in Android 4.4.3 and 4.4.4, file uploads started working again -- however, they introduced a small new bug, which is what you found here.

If you look at the "original filename", it says `IMG_20150228_161113.jpg` on Android 5.0 (which is fine) and `image:1641` on Android 4.4.4 (which is *not* fine). They dropped the file extension, and you can't do anything about it.

Since the "content type" (or MIME type) is derived from the file extension (in most browsers, including Android's `WebView`), the MIME type is unknown as well and thus shown as `application/octet-stream`.

**Comment by neonmate** [comment]
> They dropped the file extension, and you can't do anything about it.
A workaround is to use a 3rd party file explorer e. g. Solid Explorer (tested).

**Comment by mwaclawek** [comment]
Thanks, good to know there's a workaround for Android 4.4.3 and 4.4.4. However, you can't force the majority of users to use a third-party file explorer.

**Comment by EdoEscada** [comment]
Happened to me too, when produced Wordpress (along with image uploader) to be the native Android. How come..

**Comment by mwaclawek** [comment]
@EdoEscada As described above, this is a bug in the Android operating system:

 * In Android 2.2 to 4.3, file uploads worked correctly and without any problems.
 * In Android 4.4.0, 4.4.1 and 4.4.2, file uploads completely stopped working.
 * In Android 4.4.3 and 4.4.4, file uploads started working again, but Android is dropping the uploaded files' extensions, i.e. the MIME type cannot be inferred.
 * Since Android 5.0, file uploads have been working without any problems again.

Neither of us can do anything about it because it's a bug in the operating system. But you may try the workaround suggested by @neonmate.

**Comment by EdoEscada** [comment]
@mwaclawek thank you and high appreciate dor reply

**Comment by EdoEscada** [comment]
@mwaclawek thank you and high appreciate for reply
