### ISSUE TITLE
For security reasons, WebView is not allowed in privileged processes

### ISSUE THREAD

**Issue by xjpmauricio** [delight-im/Android-AdvancedWebView#146]
Does this component work with system apps ? If you use the native WebView on a system app, you'll get the exception "For security reasons, WebView is not allowed in privileged processes" along with "Error inflating class WebView"; this exception starts in WebViewFactory class.

**Comment by ocram** [comment]
Thanks for your question!

Any new insights that you may be able to share?

In general, there is probably not much difference between this library and the basic `WebView` when it comes to fundamental security restrictions in the operating system. This is because this library just builds on top of the basic view.

**Comment by xjpmauricio** [comment]
My mistake, I'm using a system app and got a "For security reasons, WebView is not allowed in privileged processes" with your component, and then I realized that your component inherits from WebView. Thanks.
