### ISSUE TITLE
Adding double click listener on AdvancedWebView disables link clicks

### ISSUE THREAD

**Issue by norrisboat** [delight-im/Android-AdvancedWebView#167]
In my use case I need something to occur when the user double taps on the view. But after adding the listener I realized when I click on links in the web view nothing happens. I really need both of them to work. Here's my code:

    mWebView.setOnTouchListener(object : View.OnTouchListener {
            private val gestureDetector = GestureDetector(this@ViewArticle, object : GestureDetector.SimpleOnGestureListener() {
                override fun onDoubleTap(e: MotionEvent): Boolean {
                    toast("double clicked")
                    return super.onDoubleTap(e)
                }
            })

            @SuppressLint("ClickableViewAccessibility")
            override fun onTouch(v: View, event: MotionEvent): Boolean {
                gestureDetector.onTouchEvent(event)
                return true
            }
        })

**Comment by ocram** [comment]
You should probably return `true` or `false` explicitly from your callbacks, i.e. `onDoubleTap` and `onTouch`. A return value of `true` means that you have consumed the event. That obviously means that you have to return `false` at least in *some* cases, otherwise the WebView will never receive the event and thus clicks inside (e.g. on links) cannot be performed.

Does that help?
