### ISSUE TITLE
onBackPressed && goback is not firing

### ISSUE THREAD

**Issue by raminrabie** [delight-im/Android-AdvancedWebView#169]
Hi

The onBackPressed is not firing and when i press back it just exit the application.

if (!mWebView.onBackPressed()) {
            return;
        }

**Comment by raminrabie** [comment]
Thanks very much. Do you know why webview is not showing box-shadows either?

**Comment by ocram** [comment]
Thanks for bringing this to our attention!

If it’s [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=794020), it appears this has already been fixed in Chromium and the fix will be available soon, as per [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=794020#c93). Can you check this?

In that case, there would be no need for us to provide any workaround, and any workaround (such as yours above) would even stop working soon again.

**Comment by raminrabie** [comment]
Thanks very much.
