### ISSUE TITLE
Issue when try open intent

### ISSUE THREAD

**Issue by ahvahsky2008** [delight-im/Android-AdvancedWebView#183]
I have button on site -  share to whatsapp. 
url - `whatsapp://send?text=http://m.xxx.ru/catalog/portativ/phones/48366/?utm_source=whatsapp&utm_medium=share&utm_campaign=05`

I catch url in this method. Its correct open whatsapp. but ifi click back button - its show error page. Whats wrong?

 ```
 @Override
    public void onPageStarted(String url, Bitmap favicon) {
        if (url.startsWith("whatsapp:") || url.startsWith("skype:") || url.startsWith("geo:"))
        {
            startActivity(new Intent("android.intent.action.VIEW", Uri.parse(url)));
        }
        else
        {
            return;
        }
    }
```
![image](https://user-images.githubusercontent.com/8035828/37240834-965de534-2461-11e8-8459-864892f3bffc.png)

**Comment by ocram** [comment]
Instead of doing this in `onPageStarted`, you have to do this in `shouldOverrideUrlLoading`. There, return `true` if you handled this yourself with WhatsApp and `false` if the `WebView` should display the URL as usual. If you use `onPageStarted`, as shown in your code, your `WebView` will continue to load the URL in the background and it will obviously fail to handle the WhatsApp scheme.
