### ISSUE TITLE
How to handle download automatically in webview

### ISSUE THREAD

**Issue by Shirishasai** [delight-im/Android-AdvancedWebView#19]
In README.md ur given this

* Downloads are handled automatically and can be listened to

   ```
   @Override
   public void onDownloadRequested(String url, String userAgent, String contentDisposition, String mimetype, long contentLength) {
       // some file is available for download
	   // either handle the download yourself or use the code below
	   
	   final String filename;
	   // ...
	   
	   if (AdvancedWebView.handleDownload(this, url, filename)) {
	       // download successfully handled
	   }
	   else {
	       // download couldn't be handled because user has disabled download manager app on the device
	       // TODO show some notice to the user
	   }
   }

Can you please provide how to handle download and what is  final String filename.
![screenshot 3](https://cloud.githubusercontent.com/assets/12455657/7647492/9272a87e-faf7-11e4-80c9-5bf6260a36b8.png)

**Comment by mwaclawek** [comment]
Thanks for your question!

You understood everything correctly and put this method in the right place. The only problem you have is the missing filename, right?

Well, that's easier than you might have thought:

Actually, you could just hard-code a filename into that method, which would look like this:

`final String filename = "my-file.txt;`

But this would *always* download and save *any* file under the name `my-file.txt`. That's probably not what you want, right?

But you can do everything you want with this filename. For example, you could add the current timestamp at the beginning of that name so that files have unique names:

`final String filename = System.currentTimeMillis()+" my-file.txt";`

Alternatively, you could include your app's name, etc.

But another important thing that you'd probably want to change is the file extension. If you know what extension the file must have, that's great, then you can hard-code it as in the examples above. But often, it won't always be a text file, so you could detect the file extension from the MIME type that is passed as a method parameter:

```
final String filename;
if (mimetype.equals("image/jpeg")) {
    filename = "my-photo.jpg";
}
else if (mimetype.equals("text/html")) {
    filename = "my-document.html";
}
else {
    // we didn't expect this MIME type and so we don't have any reasonable extension
    filename = "my-file";
}
```

Hope that helps!

**Comment by Shirishasai** [comment]
Thanks for your suggestion it worked .:-)
But am unable to cancel the download once started .Can you please help on it.

**Comment by mwaclawek** [comment]
Glad that it worked :)

Cancelling any download is not currently possible when you let this library handle the downloads automatically. This would be possible in the future, but it will require some small changes to the source code:

[Here](https://github.com/delight-im/Android-AdvancedWebView/blob/0f06e73ecee13ebc4552ac00bc0848e18662a25d/Source/src/im/delight/android/webview/AdvancedWebView.java#L1123) and [here](https://github.com/delight-im/Android-AdvancedWebView/blob/0f06e73ecee13ebc4552ac00bc0848e18662a25d/Source/src/im/delight/android/webview/AdvancedWebView.java#L1129), `DownloadManager#enqueue()` is called, which returns a unique ID for each download. Those IDs would have to be stored and be passed to `DownloadManager#remove()` when a future method (potentially named `stopDownloads()` or something like this) would be called.

Is this really important? From what we know, cancelling downloads is only rarely needed.
