### ISSUE TITLE
Webview and Facebook oAuth issue (white page)

### ISSUE THREAD

**Issue by seytone** [delight-im/Android-AdvancedWebView#195]
I have a webview application to lauch a website that integrates javascript facebook login, in the browser the login run successfull, but not in the webview app.

When I do this: **webSettings.setSupportMultipleWindows(true);** nothing happen, but if I do this: **webSettings.setSupportMultipleWindows(false)**; the webview open new window to proccess login in facebook, but after that it return just a white page, even in the second intent, the login sessión was set in the first try, but the white page shows again.

Your library is awesome, it solved many problem in my webview app, but for now, that is the only problem taht persits.

It seems to be a tipical problem with the facebook oAuth and the Androis/iOS webview.

Please, excuse my poor english.

**Comment by ocram** [comment]
It seems you just have to change how you implement multi-window support, like [here](https://github.com/delight-im/Android-AdvancedWebView/issues/180), because it doesn’t seem to be working yet in your case. Other than that, any remaining problem is probably just an issue with JavaScript and usage of OAuth.
