### ISSUE TITLE
onPageFinished calling twice

### ISSUE THREAD

**Issue by mahesh517** [delight-im/Android-AdvancedWebView#205]
HI,
onPageFinished calling twice in android 8.0 version.how to handle onPagefinish

**Comment by ocram** [comment]
Thanks!

Are you sure it’s really Android 8 that is introducing this problem?

Have you tested on Android 7 (where it works fine) and then immediately tested the *same* version on Android 8 (where the problem occurs)?

Moreover, can you test on a different Android 8 device?

Does the URL cause any redirects? What happens if you try to load `https://developer.android.com/` instead? Is the method called twice as well?

**Comment by Denny966** [comment]
It's not a problem directly related to this library, see this SO question https://stackoverflow.com/questions/18282892/android-webview-onpagefinished-called-twice

**Comment by liyujiang-gzu** [comment]
Just like what @Denny966 said，Some devices (>=Android 7.x) will  calling twice.
