### ISSUE TITLE
onDownloadRequested

### ISSUE THREAD

**Issue by sanefc23** [delight-im/Android-AdvancedWebView#216]
I'm sorry, I've tried many different ways but I still can't download a .png file from my url.

I'm pretty sure that the problem is with my url. (https://aguantaok.com.ar/creador-de-memes/) Yeah, it's in spanish.

Basically it's a meme generator, you upload an image file, put some text, and I really have no idea what it does when you press "Descargar" (Download).

When I managed it to work, it just opens a new url, with the meme generated but it doesn't dowload a .png file on the device.

Please let me know if this isn't the right place to ask, I'm new to this.

Thanks!!

**Comment by sanefc23** [comment]
If helps: when I do the same operation in Chrome it works great. Not in the webview.

**Comment by ocram** [comment]
The site is using [“html2canvas”](https://github.com/niklasvh/html2canvas) and probably something like [data URLs](https://en.wikipedia.org/wiki/Data_URI_scheme) instead of serving files directly as traditional downloads. That’s why Android’s WebView, and this library here, don’t seem to support those downloads.

If you want to test a traditional download, try it with a site like [this](https://davidwalsh.name/demo/html5-download.php).

You can probably work around this since you [can execute](https://github.com/delight-im/Android-AdvancedWebView/issues/108) JavaScript code directly from your Android application. Perhaps you could call `toDataURL` on a `HTMLCanvasElement` instance or something like that – but you’d obviously have to figure that out yourself.

**Comment by sanefc23** [comment]
Thank you so much! I'll try that out later. Thank you!
