### ISSUE TITLE
onActivityResult (int requestCode, int resultCode, Intent intent) is not called inside fragments

### ISSUE THREAD

**Issue by Whyser** [delight-im/Android-AdvancedWebView#3]
The ```onActivityResult``` is never called in ```Fragments```, it's only called in a fragments parent ```Activity```. At the moment I have to forward the ```onActivityResult``` to the correct ```Fragment``` as seen below:
```
@Override
public void onActivityResult (int requestCode, int resultCode, Intent intent) {
   if(mFragment != null) 
       mFragment.onActivityResult(requestCode, resultCode, intent);
}
```

**Comment by mwaclawek** [comment]
Thank you so much!

This commit should introduce support for Fragments:
https://github.com/delight-im/Android-AdvancedWebView/commit/7e262ed588844089c0ac28e138e7a453820d6d0a

The README has been updated as well. However, this might not work yet if you're using the "v4" support library. Can you try?

**Comment by splitbrain** [comment]
This seems not to work with the v4 support lib. My Fragment is not even recognized as Fragment by the AdvancedWebView constructor. I had to use it with getActivity() and forward the activity result as suggested by @Whyser

**Comment by mwaclawek** [comment]
Thanks for checking this and pointing out the problem, @splitbrain!

Right now, this library only supports ..

 * simple `Activity` instances without fragments
 * fragment-based `Activity` instances that use the normal Android `Fragment` class

Unfortunately, `android.app.Fragment` and `android.support.v4.app.Fragment` are two completely separate classes. Naturally so, as the latter was included in the "Android Support Library v4" specifically for those apps that need to run on devices prior to API level 11 (where there is no `Fragment` class, normally).

So without including the support library in *this* library as well, it does not know that `android.support.v4.app.Fragment` exists at all.

To avoid including the support library in this project (and always keeping it in sync with the latest version), you can circumvent the problem in one of the following ways:

 * Drop support for API levels prior to 11 ([5.9% of all users](http://developer.android.com/about/dashboards/index.html)) and use `android.app.Fragment` instead of `android.support.v4.app.Fragment`
 * Don't include this library as a JAR but by copying the source code. Include it in your app's source code directly, include the support library (you have already done this) and then change the references from `android.app.Fragment` to `android.support.v4.app.Fragment`
 * Keep using `getActivity()` and forwarding the result. Is this acceptable?

Maybe we could even include a package named `android.support.v4.app` with an empty class `Fragment` in this library. So this library would know that the class exists and when you include the support library in your app (with the right build order?), it overrides our `android.support.v4.app.Fragment` with the correct one. Don't know if that will work, however.

Does that help?

**Comment by splitbrain** [comment]
Forwarding is fine with me. Might make sense to mention it in the README
though.

**Comment by mwaclawek** [comment]
The documentation has been updated to include instructions regarding the support library:
https://github.com/delight-im/Android-AdvancedWebView/commit/b92588a36b9741c503991abaaab4924a1909c686

Hopefully, this description is okay and matches the solution you two have found, @Whyser and @splitbrain.

Thank you!
