### ISSUE TITLE
Html5 download tag

### ISSUE THREAD

**Issue by JeffersonFilho** [delight-im/Android-AdvancedWebView#31]
Hello,

I was wondering if the AdvancedWebView supports this kind of html
 <a class="fa fa-download" href="url.jpg" download></a>

Because when I click on it nothing happen and it works perfectly on chrome and other browsers.

There is anything specify that I have to do to make it work?

Thanks!

**Comment by mwaclawek** [comment]
Good question! Thank you :)

According to [this resource](http://caniuse.com/#feat=download), it should actually work in WebView since Android 4.4.

Someone reported an [issue](https://code.google.com/p/chromium/issues/detail?id=432414) for Chromium (which backs the WebView since Android 4.4) but they say that it works.

Then again, when I open [this page](https://davidwalsh.name/demo/html5-download.php) in the WebView, there's nothing happening, either. Same result as you have.

**Comment by JeffersonFilho** [comment]
Yeah I think it doesn't work because I tired everything possible and in the end I just set the heading on my API to when access that link it download the image and works great.

**Comment by mwaclawek** [comment]
Thanks for the update :)

It seems we cannot do anything here, unfortunately, so we're changing this issue to "won't fix".
