### ISSUE TITLE
file not uploading getting error:

### ISSUE THREAD

**Issue by bikeshm** [delight-im/Android-AdvancedWebView#38]
after pressing upload i am getting the following error 

01-29 04:24:11.385 32115-32115/com.example.bikesh.webviewexample I/chromium: [INFO:CONSOLE(12)] "Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png", source: data:text/html,chromewebdata (12)

**Comment by mwaclawek** [comment]
Thanks for your question!

We need much more information in order to help, of course :)

What are you trying to do? What URL are you loading in the `WebView`? What Android version did you test this on?

Did you load a `http://`, `https://` or `file:///` URL? Can you tell us the URL?

What did you do next? Did you navigate to a specific page by clicking links inside the `WebView`?

When does the error occur, exactly? When you're trying to upload a file? What is the specific HTML form that you pressed the `<input type="file">` control in? Where does the file come from that you're trying to upload?

**Comment by bikeshm** [comment]
Thanks for the quick response i fix it by using 
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
