### ISSUE TITLE
File uploads in WebView not working on KitKat (4.4.0->4.4.2)

### ISSUE THREAD

**Issue by Whyser** [delight-im/Android-AdvancedWebView#4]
This is probably a VERY known issue (and might even be unsolvable). But I thought I'd make an issue about it so that people know it won't work for KitKat 4.4.0->4.4.2. Also maybe update the README.md to state this?

It should work in KitKat 4.4.3+ though, but I haven't tested it myself.

**Comment by mwaclawek** [comment]
You're right, it's good to have this in the issues, at least. Don't know if it's necessary to have this in the README as well.

So the file uploads don't work on Android 4.4 and never will. This is because Android removed the undocumented APIs that existed *before* Android 4.4 and only introduced a new API in 5.0.

This should affect Android 4.4.3 as well.

**Comment by mwaclawek** [comment]
In order to check if file uploads are available or not, you can call the following method:

```java
AdvancedWebView.isFileUploadAvailable()
```

**Comment by wadleo** [comment]
May be you guys should try to implement this guys fix for the issue in this project, thanks.
https://github.com/henrychuangtw/Kitkat-WebView

**Comment by Mahesh-Saka** [comment]
android 5.0 lollipop file upload not working
