### ISSUE TITLE
Geolocation doesn't work

### ISSUE THREAD

**Issue by revanmj** [delight-im/Android-AdvancedWebView#5]
Could you add some support for geolocation? Right now, trying to enable support for it via normal means (like the ones discussed here: http://stackoverflow.com/questions/5329662/android-webview-geolocation ) results in breaking file uploads.

**Comment by mwaclawek** [comment]
Thank you very much!

This should now have been fixed with https://github.com/delight-im/Android-AdvancedWebView/commit/373edd522c1c536bfb179c1e07e43e9e829f6d1b and https://github.com/delight-im/Android-AdvancedWebView/commit/ae5d237aa44597c6b20a11e7ac6790efdd569018 should have introduced a convenience method.

With the latest JAR, it should be sufficient to add the permission `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` and call `mWebView.setGeolocationEnabled(true);`.

Please try this and report if it works :) Thanks!

**Comment by revanmj** [comment]
Just tried and it works fine, thanks for such a quick fix :)

**Comment by mwaclawek** [comment]
Great, thanks for testing :)

**Comment by LevelMaxBR** [comment]
Hello friends, I did the procedure you mentioned just above, but I did not get results. The alert does not appear to allow or deny the location.
Could you help me?

- Excuse my English, and congratulations on your work!

**Comment by ocram** [comment]
@LevelMaxBR Let’s keep the discussion regarding your problem in https://github.com/delight-im/Android-AdvancedWebView/issues/173
