### ISSUE TITLE
AddHttpHeader does not work 

### ISSUE THREAD

**Issue by ashraful29** [delight-im/Android-AdvancedWebView#52]
AddHttpHeader does not work  when use post url in Webview

**Comment by mwaclawek** [comment]
Thank you very much!

As you can see [here](https://github.com/delight-im/Android-AdvancedWebView/blob/76be2be8d011e17f4ffc777975b4ce3107f2713d/Source/library/src/main/java/im/delight/android/webview/AdvancedWebView.java#L268), it's actually (and unfortunately) expected behaviour and documented accordingly.

I'm afraid the only solution to this problem would be using `WebViewClient#shouldInterceptRequest` (available on API levels 11+ and 21+, respectively) instead of `WebViewClient#shouldOverrideUrlLoading`.

But in that case, we would have to do *all* resource requests (pages, images, CSS, JS, etc.) ourselves, i.e. download them with a HTTP client.

But you can do this yourself already without changing this library: Just implement those `WebViewClient` methods yourself and apply your custom `WebViewClient` instance via `setWebViewClient`.
