### ISSUE TITLE
White screen and nothing shows

### ISSUE THREAD

**Issue by EgyptianM** [delight-im/Android-AdvancedWebView#55]
Hi,
Thank you for your efforts.
I'm trying to use your awesome library but I'm getting white page most of the time.
I tried it with m.facebook.com and my site doblist.com they are the same.
I'm trying the sample included with the library.
And I noticed that it's more slow than the original webView 
I tried my m.facebook.com and my site on the original and they are working fine.
In the library it show a toast with "Finished loading" then a toast with the title but nothing shows in the webview.
Thank you very much

**Comment by mwaclawek** [comment]
Thanks for your feedback!

 1. If this was really a bug in this library, I think more people would have noticed it already. I don't see that wrong behavior myself, either. I could be wrong, but the *more likely* reason is that something in your configuration or setup is wrong. Can you check this again and compare with the README? Thank you.
 1. Yes, checking against popular sites such as Facebook is always the bettermethod for debugging. Thanks for doing this!
 1. I really doubt that this library is significantly slower than the original `WebView`. That's because this library here is just a very thin wrapper around the original component, and all the heavy lifting (parsing, rendering, etc.) is done in the original component. How did you arrive at this conclusion, by the way? Did you *feel* it or did you *measure* it?
 1. What Android version are you running this on?

**Comment by EgyptianM** [comment]
Hello @mwaclawek ,
Sorry for the late reply I'm so busy these days.
1. This issue is solved by itself I don't know how but most likely it was some wrong configuration or something related to my internet connection at that moment. But I'm still getting a white page during page loading and after title is received the page shows while in normal webview the page shows during loading and this is better for me

3. It's really slower than normal webview, it's very obvious for me that it takes longer time to load the page, note that I'm testing against the same page on both webviews. I felt it because it takes noticeable time that makes me sure. BTW how can I measure it? Is there any methods to do that?

4. I'm using my phone with android version 4.2.2.

Thank you very much for your great efforts and making this great library.
Have a nice day.

**Comment by mwaclawek** [comment]
Thanks, great to hear that the issue has been resolved :)

 1. Since you stated that you used the example included with this library, the white screen during page load is intentional. In the `Activity`, you can see that the `WebView` is hidden in `onPageStarted(...)` and only shown again in `onPageFinished(...)`. If you don't want this to happen, just remove these lines.
 1. --
 1. In order to measure this, get the `System.nanoTime()` in `onPageStarted(...)`. Then, in `onPageFinished(...)`, get `System.nanoTime()` again. Check the difference and divide it by 1 million to get the duration in milliseconds. For the original `WebView`, you'd have to do this as well, but you'll find the two methods in `WebViewClient` only.
 1. Maybe that goes away when you change the thing from (1).
