### ISSUE TITLE
Filename for downloads

### ISSUE THREAD

**Issue by thijseend** [delight-im/Android-AdvancedWebView#66]
Hello,

I've added this webview to my project only there is one thing that doesn't work.
When I try to add the download section in my activity the second filename turns red??

    private AdvancedWebView mWebView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mWebView = (AdvancedWebView) findViewById(R.id.webview);
        mWebView.setListener(this, this);
        mWebView.loadUrl("http://myurl");

        // ...
    }

    @SuppressLint("NewApi")
    @Override
    protected void onResume() {
        super.onResume();
        mWebView.onResume();
        // ...
    }

    @SuppressLint("NewApi")
    @Override
    protected void onPause() {
        mWebView.onPause();
        // ...
        super.onPause();
    }

    @Override
    protected void onDestroy() {
        mWebView.onDestroy();
        // ...
        super.onDestroy();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);
        mWebView.onActivityResult(requestCode, resultCode, intent);
        // ...
    }

    @Override
    public void onBackPressed() {
        if (!mWebView.onBackPressed()) { return; }
        // ...
        super.onBackPressed();
    }

    @Override
    public void onPageStarted(String url, Bitmap favicon) { }

    @Override
    public void onPageFinished(String url) { }

    @Override
    public void onPageError(int errorCode, String description, String failingUrl) { }

    @Override
    public void onDownloadRequested(String url, String userAgent, String contentDisposition, String mimetype, long contentLength) {
        // some file is available for download
        // either handle the download yourself or use the code below

        final String filename;
        // ...

        if (AdvancedWebView.handleDownload(this, url, filename)) {
            // download successfully handled
        }
        else {
            // download couldn't be handled because user has disabled download manager app on the device
            // TODO show some notice to the user
        }
    }

    @Override
    public void onExternalPageRequest(String url) { }

The word filename gets red in the next part: (this, url, filename)) {

**Comment by thijseend** [comment]
Okeee, found out that if i change the first filename in the code it downloads but with the filename i provided.


        final String filename = "cool.mp3";
        // ...

        if (AdvancedWebView.handleDownload(this, url, filename)) {
            // download successfully handled
        }
        else {
            // download couldn't be handled because user has disabled download manager app on the device
            // TODO show some notice to the user
        }
    }

but how do i change this so that it gets the filename from the server?

**Comment by mwaclawek** [comment]
Thanks for your question!

Glad you've figured out the solution to your original problem already. The code that you copied from the README was indeed not complete yet. The variable declaration for the `filename` variable was there,. but the assignment was not. That's what the `// ...` comment was to represent. So we should probably improve the example to make this absolutely clear.

Regarding your new question, i.e. how to determine the filename, you got this right as well: Currently, the intended solution is that you hard-code the filename as you did or build the filename with some conditional structures, etc.

If you want this to work automatically, https://github.com/delight-im/Android-AdvancedWebView/issues/32 is probably related. The `URLUtil.guessFileName` method may be what you're looking for. Can you try it? You should have all the "ingredients" already because the required parameters should be what you've received in the `onDownloadRequested` method.

Hope that helps! If it works, we can add that feature to this library natively.

**Comment by thijseend** [comment]
Heey,

I've found the solution to my problem:

`String filename = URLUtil.guessFileName(url,
                contentDisposition, mimetype);
`
Now it works very well!

**Comment by mwaclawek** [comment]
Yes, that's what we proposed. Thanks for testing!

Built-in support for this has been added in https://github.com/delight-im/Android-AdvancedWebView/commit/d5cb1e5b0f8ff818b5aaca69edf03b74d931f92c now. In order to use this, just update the dependency as shown in the README and follow the migration guide from `Migration.md`.
