### ISSUE TITLE
forbide jumping automatically

### ISSUE THREAD

**Issue by hellyeahhhhhhh** [delight-im/Android-AdvancedWebView#67]
I loaded a url with AdvancedWebView, (http://music.163.com/#/album/1802412), contents on this site showed shortly, then failure occurred, saying "Can't find the page. the page **_orpheus://albun?1802412_** is not available now, blabla blabla~~~~~~~"
I think it was trying jumping to the APP.
How can I disable the automatical jumping?
Thank you :)

**Comment by mwaclawek** [comment]
1. Set a custom `WebViewClient` (if you haven't done this already) using `setWebViewClient(...)`
 1. In your custom `WebViewClient`, implement `shouldOverrideUrlLoading(...)`
 1. In that method, check if the URL starts with `orpheus://`
 1. Return `true` if it does in order to ignore the request

Does this help?

**Comment by hellyeahhhhhhh** [comment]
@mwaclawek 
It worked!!
Thank you very much!
