### ISSUE TITLE
Failed to resolve: com.github.delight-im:Android-AdvancedWebView:v3.0.0

### ISSUE THREAD

**Issue by LuisHCK** [delight-im/Android-AdvancedWebView#69]
In my build.gradle i've added the jitpack repo, but the error persists 
`allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}`

`Error:(25, 13) Failed to resolve: com.github.delight-im:Android-AdvancedWebView:v3.0.0`

**Comment by mwaclawek** [comment]
Thanks for your feedback!

That's really strange, since it's working perfectly for us and there have been many tests now which confirmed that it's working.

Are you sure that you've used the right `build.gradle` files for every step? That is, the one in the *root* for the repository definition and the one in the *app module* for the dependency definition?

As you can see [here](https://jitpack.io/com/github/delight-im/Android-AdvancedWebView/v3.0.0/Android-AdvancedWebView-v3.0.0.aar), the AAR bundle of this library does indeed exist in our Maven repository. Can you check whether you have access to this file at least in your web browser?

Alternatively, can you try an older version of the dependency that *provably* worked? For example this one, which is the direct predecessor to the current version:

```
compile 'com.github.delight-im:Android-AdvancedWebView:v2.1.1'
```

Thank you!

**Comment by mwaclawek** [comment]
@LuisHCK Did you solve this problem? Can you explain what you did? I heard migrating from Java 7 to Java 8 might help.

**Comment by chrisserra** [comment]
Getting the same issue.

**Comment by vamsipidugu** [comment]
add
maven { url "https://jitpack.io" }

inside allprojects repositories and try

**Comment by Andrfas** [comment]
Adding `maven { url "https://jitpack.io" }` doesn't work for me

**Comment by Dilpenny** [comment]
Works
