### ISSUE TITLE
Why not compiling to APK

### ISSUE THREAD

**Issue by machado-rev** [delight-im/Android-AdvancedWebView#70]
Why? I just see .aar files.. (I don't understand about Android Developtment)
I am using Android SDK

**Comment by mwaclawek** [comment]
Where do you see AAR files? You shouldn't have to see or handle AAR files yourself.

APK files are for apps. This is what you build, but not what this here is. This is a library.

JAR files or AAR files are for libraries, so that's what we have here.

I'd suggest you read a bit about Android first, including its official documentation.
