### ISSUE TITLE
Android 5.0.x TimePicker bug

### ISSUE THREAD

**Issue by GitWessel** [delight-im/Android-AdvancedWebView#77]
Sinds android 5.0.x is the time picker bugged. The ok button is gone only the setting en cancel button is active. Possible to override this datetime picker with the google chrome to fix the problem?

**Comment by GitWessel** [comment]
Take a look at: []( https://bugs.chromium.org/p/chromium/issues/detail?id=434695)
They solved it for version 5.1.x But still got some tablets running on 5.0.x which are not able to upgrade to 5.1.x (samsung tab 4, 10.1 inch)

Anyway you can solve this in de webview?

**Comment by mwaclawek** [comment]
Thanks for your feedback!

I see your problem, but unfortunately, I currently don't know of any way to fix this.

Since this is a bug in the original `WebView` and not one in this library (although we *might* be able to fix it *here*), I'm closing this issue. If anybody finds a solution that can be included in this library, I'll happily integrate it.

**Comment by GitWessel** [comment]
Asked the Webview they finally solved the problem in new update now.

**Comment by ocram** [comment]
@GitWessel Thanks! As the Android System WebView is updatable via the Play Store on Android 5.0+, I guess a fix would get to all affected Android versions then.
