### ISSUE TITLE
WebView Not loading after restarting the Activity

### ISSUE THREAD

**Issue by laxmikant23** [delight-im/Android-AdvancedWebView#79]
Load any HTML page with more 80 or 90 pages and scroll to the last position.
Then close the activity and reopen .

Webview not getting loaded as Android Webview is lazy and not clearing its cache i guess.
Please suggest a solution ASAP

**Comment by mwaclawek** [comment]
Thanks for your report!

In order to reproduce this problem and perhaps find a solution, we'd need at least three pieces of information:

 * Can you provide some public URL to a web page where this happens for you?
 * What are 80 pages exactly? Content with 80 times the height of the window?
 * What device and Android version are you testing this on?

**Comment by laxmikant23** [comment]
1. Load the Google License Page by creating a HTML 
2. Height is Match_Parent
3. On All android devices.

**Comment by mwaclawek** [comment]
1. What is "the Google License Page"? I don't see any public URL here, neither an attached HTML file. Sorry!
 1. That's the height of the `View` in Android. But what's the height of the *content* in the *HTML* page? From your description, it must be something that is about 80 times the height of the screen so that you have a "page with more 80 or 90 pages".
 1. Really? Did you test it on all devices? Why not tell something about your device and Android version first? That might be helpful :)
