### ISSUE TITLE
Describe installation process in detail

### ISSUE THREAD

**Issue by thusfar7** [delight-im/Android-AdvancedWebView#90]
I would appreciate if you could describe installation process in detail. I've been trying to install this for the last hour and still havent accomplished anything.

**Comment by ocram** [comment]
Thanks for your question and sorry for the problems that you experienced!

Can you tell us what you did so far and where the problems occurred or where you didn't know what to do next? You should refer to the "Installation" and "Usage" sections of the README.

We can then improve the documentation if we find something that is lacking there.

**Comment by thusfar7** [comment]
Why inst there shouldOverrideUrlLoading method?

**Comment by ocram** [comment]
There is!

But that isn't related to the installation process, anyway, is it? If you've come that far, installation seems to be done already. Any question regarding the actual installation process?

URL overriding is done exactly like it's done with the plain `WebView`, so that's why it doesn't need any documentation. Alternatively, there's a simpler solution via `addPermittedHostname` and a callback, as documented in the README. That works for most use cases.
