### ISSUE TITLE
W/cr_BindingManager: Cannot call determinedVisibility()

### ISSUE THREAD

**Issue by ntaloventi** [delight-im/Android-AdvancedWebView#94]
same error with webview

**Comment by ocram** [comment]
You get the same error (on the same page) with Android's built-in `WebView`?

**Comment by ntaloventi** [comment]
dear ocram, 

thanks for reply, looks like something miss on my code or maybe else...
topology is not direct to main page:
apps => myserver.com => company.payment.gateway => payment.provider.checkout

I think in "company.payment.gateway" there some cookie/session that should be stored, so when another redirect to "payment.provider.checkout" its rejected...

and now I'm using chrometabs to achieve that

**Comment by ocram** [comment]
@ntaloventi Thank you!

Does that mean this issue is obsolete? If you switched to a solution using custom Chrome tabs, we cannot re-produce this problem anymore, I guess, and you don't mind anymore.

Custom Chrome tabs are, of course, not an equivalent solution. Sometimes they're better, sometimes they're worse. They serve slightly different purposes.

Both cookies in general and third-party cookies can be disabled with this library, but they should be enabled by default.
